#!/bin/bash

command -v tput > /dev/null

tput clear
cat  << 'EOF'
     ___   ____    __    ____  _______     _______.  ______   .___  ___.  _______ 
    /   \  \   \  /  \  /   / |   ____|   /       | /  __  \  |   \/   | |   ____|
   /  ^  \  \   \/    \/   /  |  |__     |   (----`|  |  |  | |  \  /  | |  |__   
  /  /_\  \  \            /   |   __|     \   \    |  |  |  | |  |\/|  | |   __|  
 /  _____  \  \    /\    /    |  |____.----)   |   |  `--'  | |  |  |  | |  |____ 
/__/     \__\  \__/  \__/     |_______|_______/     \______/  |__|  |__| |_______|
                                                                                  
 _______  .______       __   __       __        __  
|       \ |   _  \     |  | |  |     |  |      |  | 
|  .--.  ||  |_)  |    |  | |  |     |  |      |  | 
|  |  |  ||      /     |  | |  |     |  |      |  | 
|  '--'  ||  |\  \----.|  | |  `----.|  `----. |__| 
|_______/ | _| `._____||__| |_______||_______| (__) 
                                                   
EOF

terraform_dd() {
    command -v unzip > /dev/null
    if [ $? -eq 1 ]; then
        sudo apt-get -y install unzip
    fi

	command -v terraform
	if [ $? -eq 1 ]; then
		curl -X GET https://www.terraform.io/downloads.html 2>/dev/null | grep "\.\zip" | grep "terraform" > tf_list
	    if [ ${FZF} == "true" ]; then
	       	while read -r line; do
	           	echo ${line} | awk -F'"' '{print $2}' | awk -F'"' '{print $1}'
	       	done < tf_list | uniq  > list
	       	SELECTED=$(cat list | fzf --reverse --no-mouse --height=15 --bind=left:page-up,right:page-down)
			if [ ! ${SELECTED}  ]; then
				return
			else
				ZIP_NAME=$(echo $SELECTED | awk -F'/' '{print $NF}')
		        echo $ZIP_NAME
		        wget $SELECTED
		        unzip $ZIP_NAME
		        chmod +x terraform
		        mv terraform /usr/local/bin
		        rm -rf tf_list
		        rm -rf list
		        rm -rf $ZIP_NAME
			fi
	    fi
	fi
}

go_dd() {
	command -v go
	if [ $? -eq 1 ]; then
		exp="go([[:alnum:]\.]*)\.src.*"

		curl -X GET https://golang.org/dl/ 2>/dev/null > log

		if [ "${FZF}" == "true" ]; then
			while read -r line; do
				if [[ "${line}" =~ ${exp} ]]; then
					echo "${BASH_REMATCH[1]}"
				fi
			done < log | sort --version-sort --reverse | uniq > list
			SELECTED=$(cat list | fzf --reverse --no-mouse --height=15 --bind=left:page-up,right:page-down)
		fi

		GO_URL=$(cat log | grep "go${SELECTED}" | grep linux-amd64 | sed -n 1p | awk -F' ' '{print $4}' | awk -F'"' '{print $2}')
		GO_BINARY=$(echo $GO_URL | awk -F'/' '{print $5}')
		wget ${GO_URL}
		tar -C /usr/local -xvf ${GO_BINARY}
		rm -rf ${GO_BINARY}

		FIND_GO=$(cat ~/.bashrc | grep "go/bin" | wc -l)
		if [ ${FIND_GO} -eq 0 ]; then
	    	echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
		fi
		FIND_GOPATH=$(cat ~/.bashrc | grep "GOPATH" | wc -l)
		if [ ${FIND_GOPATH} -eq 0 ]; then
			echo 'export GOPATH=$(go env GOPATH)' >> ~/.bashrc
		fi
		FIND_GOROOT=$(cat ~/.bashrc | grep "GOROOT" | wc -l)
		if [ ${FIND_GOROOT} -eq 0 ]; then
    		echo 'export GOROOT=/usr/local/go' >> ~/.bashrc
		fi
		rm -rf list
		rm -rf log
	else
		go get -v golang.org/x/tools/cmd/godoc
	fi
}

aws-cli_dd () {
	command -v pip3 > /dev/null
	if [ $? -eq 1 ]; then
		sudo apt -y install jq
		sudo apt -y install python3
		sudo apt -y install python3-distutils
		curl -O https://bootstrap.pypa.io/get-pip.py 2>/dev/null 
		python3 get-pip.py --user
        echo "PATH=~/.local/bin:$PATH" >> ~/.bashrc
        export PATH=~/.local/bin:$PATH
        pip3 --version
        pip3 install awscli --upgrade --user
    else
		command -v aws > /dev/null
		if [ $? -eq 1 ]; then
	        pip3 --version
    	    pip3 install awscli --upgrade --user
		fi
    fi
	rm -rf get-pip.py
}

aws-iam-authenticator_dd () {
	command -v aws-iam-authenticator > /dev/null
	if [ $? -eq 1 ]; then
		curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.14.6/2019-08-22/bin/linux/amd64/aws-iam-authenticator 2>/dev/null
		chmod +x ./aws-iam-authenticator
		mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
	fi
}

nodejs_dd() {
	command -v node > /dev/null
	if [ $? -eq 1 ]; then
		apt-get -y install nodejs
		apt-get -y install npm
	fi
}











# install fzf
command -v fzf > /dev/null
if [ $? -eq 1 ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
    exit 0
else
    FZF=true
fi

# intro
echo -e "| ============================================================= |"
echo -e "| Install all your application in linux for using drill-down!!! |"
echo -e "| ============================================================= |"

# main
while :
do
	CMD_SELECTED=$(cat ~/.ad/resources/cmd | fzf --reverse --no-mouse --height=15 --bind=left:page-up,right:page-down)
	if [ "${CMD_SELECTED}" == "" ]; then
		break
	else
		echo "${CMD_SELECTED}"
		${CMD_SELECTED}_dd
	fi
done
